esphome:
  name: esp32-for-testing-mlx9060_2
  includes:
  
  libraries:
    - Wire
    - FS
    - SPIFFS
  
 


external_components:
  - source: 
      type: local
      path: components
    components: [camera_mlx90640]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:
    
text_sensor:

sensor:
    
camera_mlx90640:
  id: thermal_cam
  update_interval: 20s
  sda: 25  # I2C SDA PIN
  scl: 26  # I2C SCL PIN
  frequency: 400000  # I2C Clock Frequency
  address: 0x33 # MLX90640 Address
  mintemp: 24 # Minimal temperature for color mapping
  maxtemp: 35 # Maximal temperature for color mapping
  refresh_rate: 0x05 # For 16Hz or 0x04 for 8Hz
  filter_level: 10.0 # Level in degree of the filter. If there a difference above the level, the pixel is approximated by the average of the next two pixels
  min_temperature:
      name: "MLX90640 Min temperature"
  max_temperature:
      name: "MLX90640 Max temperature"
  mean_temperature:
      name: "MLX90640 Mean temperature"
  median_temperature:
      name: "MLX90640 Median temperature"
  
  



    #sensors:
web_server:
  port: 80
