esphome:
  name: esp32-for-testing-mlx9060
  includes:
    - components/mlx90640/mlx_driver.h
    - components/mlx90640/mlx_api.h


external_components:
  - source: 
      type: local
      path: components
    components: [mlx90640]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:
    
i2c:
  sda: 21
  scl: 22
  scan: false
  id: bus_i2c



#mlx90640:
#  id: test_mlx9040

sensor:
  - platform: mlx90640
    update_interval: 20s
    i2c_id: bus_i2c
    id: test_mlx9040
    temperature:
      name: "MLX90640 Temperature"
    min_temperature:
      name: "MLX90640 Min temperature"
    max_temperature:
      name: "MLX90640 Max temperature"

    #sensors:
     
