esphome:
  name: esp32-for-testing-mlx9060
  includes:
  libraries:
    - Wire

external_components:
  - source: 
      type: local
      path: components
    components: [mlx90640]

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "testing"

ota:
  password: "testing"

wifi:
  ssid: "Livebox-36B0"
  password: "4CHfRsdx9C9c8VdH2t"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-For-Testing-Mlx9060"
    password: "Rhg1rO0ix8Oz"

captive_portal:
    
text_sensor:

sensor:
    
mlx90640:
  id: thermal_cam
  update_interval: 20s
  sda: 25  # I2C SDA PIN
  scl: 26  # I2C SCL PIN
  frequency: 450000  # I2C Clock Frequency
  address: 0x33 # MLX90640 Address
  
  pixel_data: # the pixel data text_sensor 
    id: pixel_text_sensor
    name: Pixel Camera data
    disabled_by_default: false
 
  min_temperature:
      name: "MLX90640 Min temperature"
  max_temperature:
      name: "MLX90640 Max temperature"
  
  



    #sensors:
web_server:
  port: 80
